### ISSUE TITLE
Linux Package of the tool (FR)

### ISSUE THREAD

**Issue by aasyria** [cyberark/KubiScan#27]
I would like to have a running Linux binary of this tool because almost of the pen tests are offline 
I tried to use pyinstaller for this propose but did not work.
thanx

**Comment by g3rzi** [comment]
Hi, thank you @aasyria.  
We will check it and update.  

But even if the pentest is offline, you can run the it as Python and not from `docker` (which need internet connection to download the file).

I wrote [here](https://github.com/cyberark/KubiScan#directly-with-python3) how to use it with Python so you can use it offline.
