### ISSUE TITLE
Looking for alpine based docker

### ISSUE THREAD

**Issue by prasenforu** [cyberark/KubiScan#4]
Looking for alpine based docker make lightweight

**Comment by g3rzi** [comment]
As far as I remember I had problems to install it on alpine because of python3. But I will check again if it possible to make it much lighter.

**Comment by g3rzi** [comment]
I checked, I wasn't able to install it with the regular `pip3` installer but succeeded to install it from the source by:  
```
git clone --recursive https://github.com/kubernetes-client/python.git
cd python/
python3 setup.py install
```
* make sure requests module is installed (`pip3 install requests`)

I will make an image with alpine, and update you once it done.

**Comment by prasenforu** [comment]
waiting ... 
Thanks !!

**Comment by g3rzi** [comment]
I just updated Dockerfiles that supports alpine image.  I will update this case one it will be in the Dokcer Hub.

**Comment by prasenforu** [comment]
Thanks,

Let me check.

Will update you.

**Comment by prasenforu** [comment]
It's working & reduced image size.

**Comment by g3rzi** [comment]
Great. I also work to upload it to the public Docker Hub repository. I will update when it will be ready.
