### ISSUE TITLE
Support for kubeconfig credentials directly in kubeconfig file

### ISSUE THREAD

**Issue by MMquant** [cyberark/KubiScan#58]
I have kubeconfig file which doesn't contain

```
certificate-authority:
client-certificate:
```

keys.

Instead the credentials are included directly in the kubeconfig file via

```
certificate-authority-data:
client-certificate-data:
```

Can I pass such kubeconfig directly to kubiscan or do I need to move the credentials into separate files and use
```
certificate-authority:
client-certificate:
```
?

**Comment by g3rzi** [comment]
Hi,

It should work because we using `config.load_kube_config()` which should load the config file as is:
https://github.com/cyberark/KubiScan/blob/b8e7f427692953d59284eb8d23033371c9026bdb/api/api_client.py#L66  


If it doesn't work for you, let us know and we will fix it.
