### ISSUE TITLE
Enhancements for output

### ISSUE THREAD

**Issue by cosad3s** [cyberark/KubiScan#60]
For a better integration with other tool, it could be interesting to have options to:

- Hide the banner (*Kind of quiet mode with* `-q`)
- Write the output matrix to a file (`-o outputfile.txt`). *It can open future opportunities on file format: json or yaml for exemple.*

Thanks for this great tool!

**Comment by g3rzi** [comment]
Thanks, it sounds a good idea, we will check it and update :)

**Comment by g3rzi** [comment]
Hi, we added an option for output, including JSON and an option to add\remove the colors of the priority in the table.
