### ISSUE TITLE
Failed chmod when not specifying AWS info

### ISSUE THREAD

**Issue by elreydetoda** [cyberark/KubiScan#66]
## Summary

When not providing an [`aws_dir`](https://github.com/cyberark/KubiScan/blob/cd670a671454c99487327942332fa5a6697037f3/docker_run.sh#L25-L30) as an argument to the [`./docker_run.sh` script](https://github.com/cyberark/KubiScan/blob/cd670a671454c99487327942332fa5a6697037f3/docker_run.sh), the [`mkdir -p` command](https://github.com/cyberark/KubiScan/blob/cd670a671454c99487327942332fa5a6697037f3/docker_run.sh#L28) doesn't run. Causing the [`chmod` command](https://github.com/cyberark/KubiScan/blob/cd670a671454c99487327942332fa5a6697037f3/docker_run.sh#L109) to fail.

While this doesn't prevent you from exec'ing inside the container it is still confusing (made me think the script didn't finish initially).

## Steps to Reproduce

1. Clone repo
2. Execute `./docker_run.sh ~/.kube/config`
3. See error

(the same error happens no matter if I'm using @2niknatan's `natan2nik/kubiscan` image or build locally and use that image's name)

## Expected Results

No errors (i.e. picture below)

![image](https://github.com/cyberark/KubiScan/assets/10230166/a377686c-875d-489c-896c-20d85ad9162c)

## Actual Results

`chmod`  error

![image](https://github.com/cyberark/KubiScan/assets/10230166/c787c541-5506-4fbe-9c5d-4a1e9526aa51)

## Reproducible

   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

commit: cd670a671454c99487327942332fa5a6697037f3 
(current master branch's latest commit)

## Environment setup

In proxmox VM running Kali Linux 2023.1 with docker version:
```
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:28 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.9
  Git commit:       9dbdbd4
  Built:            Fri May  5 21:18:28 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Effectively running in this [Vagrantfile](https://github.com/elreydetoda/vagrant-files/blob/632aeb93220c795a2f188ddee6b7e29fd754266b/elrey741_kali-linux_amd64/Vagrantfile) (used the [same script](https://github.com/elreydetoda/packer-kali_linux/blob/9b55291d17df7f1859bc456272c5797f52d529fc/prov_packer/docker.sh) to install docker).

## Additional Information

N/a

**Comment by g3rzi** [comment]
Thank you, I appreciate your elaboration on the bug.
I understand the problem, the  `-f` will suppress the errors, usually I prefer to know if there are problems but in this specific issue I think your solution is good enough.
