### ISSUE TITLE
setup file

### ISSUE THREAD

**Issue by dualfade** [cyberark/KubiScan#68]
Would it be possible to create a setup.py or a pyproject.toml so I could package this correctly for blackarch linux ?

Thank you.
Sincerely

**Comment by g3rzi** [comment]
Yes, but we are currently working on other priority bugs in different projects so it might take time.
I will check about that.

**Comment by dualfade** [comment]
Going to close down my request. I tested this with hatch and works in seconds. But I have an ongoing PR that is just sitting there. I will revisit later. Thanks.
