### ISSUE TITLE
JSON output failure

### ISSUE THREAD

**Issue by koengu** [cyberark/KubiScan#71]
Hi
I executed below command to store output in JSON, but KubiScan only stores ] in JSONfile.
`$ sudo python3 /usr/bin/KubiScan/KubiScan.py -a -q -j ~/a.json`

The out put is:
```
$ cat ~/a.json
]

```

**Comment by g3rzi** [comment]
Thanks for reporting, we will check it and update accordingly.

**Comment by g3rzi** [comment]
Hi @koengu, 
A new fix was merged, can you check? 
It should work now.
