### ISSUE TITLE
Kubernetes PSP (Pod Security Policy) using kubiscan

### ISSUE THREAD

**Issue by prasenforu** [cyberark/KubiScan#9]
In my last discussion we discussed about risky pod. In this context if you think kubernetes PSP (Pod Security Policy) can be implemented along with kubiscan that will be great as a part of enhancement.

**Comment by g3rzi** [comment]
It can be implemented but this is a new vector. The focus of KubiScan was to scan for risky **permissions** and how they affect the roles, bindings, users and pods. 
We can add PSP but we need to understand what we want to get from it. Risky PSPs ? Like, PSPs that if someone will use them, it will create **privileged containers**? In such, case we can just go and search for privileged containers directly (by inspecting each Pod\container YAML).

**Comment by prasenforu** [comment]
PSP cover lots but if we focus below ..

Pods root privileges
Host PID access
Host network access
Host port access
Host volume access

I think that will be enough coverage in addition to risky pod.

**Comment by g3rzi** [comment]
Why not just check the configuration of each pod\container and check its security context?

**Comment by prasenforu** [comment]
Check when pod going to start/launch

**Comment by g3rzi** [comment]
I added an option to check the security context of pods and search for pods with security context of `privileged`, root user, dangerous capabilities and if the flag allow privilege escalation is set.

**Comment by prasenforu** [comment]
How to use? 

Same risky pod (-rp) switch will give result along with ?

**Comment by g3rzi** [comment]
`-pp`

**Comment by prasenforu** [comment]
Its working fine but its not capturing hostnetwork.

If I mention pod defination ```hostNetwork: true``` or ```hostPort``` then its not capturing.

Basically usage of the hostPort is considered a privileged operation on OpenShift.

My target is it should capture below all 

Host PID access
Host network access
Host port access
Host volume access
 
trying to make this tool compatible with all kubernetes flavor in including openshift.

**Comment by g3rzi** [comment]
I can see the Host PID and Host network fields in the PodSpec:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podspec-v1-core

Where the Host port should be find?

Regarding the volume access I will check it but maybe I have something that already does it l, this is the `-psv` switch that shows all the mounted volumes to the pods.
We also have the `-pse` that shows all the environment variables mounted to the pods.

**Comment by prasenforu** [comment]
```hostport``` as use as follows ...

![image](https://user-images.githubusercontent.com/19322497/56076431-84048880-5dee-11e9-84dd-d72a7f95e9f7.png)

```psv```  Show Pods that has access to the secret data through a Volume 
and
```pse``` Show Pods that has access to the secret data through a Environment.

I do not think it does any ```Host volume access```

**Comment by g3rzi** [comment]
Regarding the `hostPort`, I don't understand why it is being considered as a privileged operation on OpenShift. 
When we are talking about privileged containers, the idea is that if an attacker is inside the container, he has root privileged, high capabilities, break out to the host or control other containers. 
An exposed port, just shows that exposed port of the container on the master. It doesn't mean you can do something interesting with this if I compare it to the other operations I mentioned.

**Comment by prasenforu** [comment]
It's a security whole, if somehow anyone use hostport in pod then that port is locked in that host where that container deployed.
Nobody can use that port and attacker can try to access cluster using hostport.

**Comment by prasenforu** [comment]
In PSP (Pod Security Policy) below link I think you capturing only "privileged" field.

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#what-is-a-pod-security-policy

If you consider following field also then it will be more effective regarding ```privileged/risky pod```

![image](https://user-images.githubusercontent.com/19322497/62677333-9624bb00-b9cb-11e9-9236-ca33715ad848.png)

**Comment by g3rzi** [comment]
Yes, it sounds like a good suggestion.
I will check it and update.

**Comment by prasenforu** [comment]
Any update?

**Comment by g3rzi** [comment]
Added support to `hostPID` and `hostIPC`.
Regarding `readOnlyRootFilesystem` I saw that the default is `false` which indicates that you can write to the root filesystem. 
As this is the default, it will make lots of "noise" because most of the pods will have this field set to false, don't you think ?  We will get probably all the pods appeared as "privileged".

**Comment by prasenforu** [comment]
if someone use ```readOnlyRootFilesystem```  ```true```  then kubiscan should catch.

![image](https://user-images.githubusercontent.com/19322497/63001290-f23a8400-be90-11e9-804f-8902187f55ff.png)

**Comment by g3rzi** [comment]
I did some tests with:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep 99d"]
    ports:
      - containerPort: 6666
        hostPort: 6666
  hostNetwork: true
  hostIPC: true
  hostPID: true
EOF
```
The `hostNetwork` field show more containers:
![image](https://user-images.githubusercontent.com/11998736/63010591-578d7580-be8f-11e9-8bfe-1c1dd931391a.png)


I guess I just need to check the `allowedHostPath`, I need to decide to what feature to add it (`-psv` or `-pp`).

**Comment by prasenforu** [comment]
yes that is OK, normally people should check pod under namespace, under ```kube-system``` it will give.

The features you should maintain under ``-pp``

**Comment by prasenforu** [comment]
Put all PSP (Pod Security Policy) related things under ```-pp```

**Comment by prasenforu** [comment]
I checked but what I noticed earlier ```-pp```  works with ```-n <namespace>```

Now its show privileged pod under all namespace.

**Comment by g3rzi** [comment]
I now prints also the host paths which make it more "noisy":
![image](https://user-images.githubusercontent.com/11998736/63031792-46f3f400-bebd-11e9-90f9-643697377d12.png)


Regarding the namespaces.
If you not specify a namespace it will print for all the namespaces. Other option is to make that if you not specify a namespace it will print for the "default" namespace. But I think it is find like that.

You can use namespaces, for example: `kubiscan -pp -ns default`:  
![image](https://user-images.githubusercontent.com/11998736/63032071-c97cb380-bebd-11e9-9110-af69a2270213.png)

**Comment by g3rzi** [comment]
Notice to use `-ns` instead of `-n`. 
I created `-ns` for `--namespaces` because the `-n` was taken for `--name`.

**Comment by prasenforu** [comment]
It was my typo. But I always use -ns.

Tomorrow I will check & update you.

By the way can send me Hi in my whatsup no. +919830736299

**Comment by prasenforu** [comment]
If you using whatsup.

**Comment by g3rzi** [comment]
No twitter or linkedin?

**Comment by prasenforu** [comment]
No Twitter but Linkedin yes. :)

**Comment by g3rzi** [comment]
OK, so contact me: Eviatar Gerzi

**Comment by prasenforu** [comment]
Sure

**Comment by prasenforu** [comment]
closing
